version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: infinum_chat 
      MYSQL_PASSWORD: user_password  
    volumes:
      - mysql-data:/var/lib/mysql       
      - ./infinum_chat.sql:/docker-entrypoint-initdb.d/infinum_chat.sql  
    ports:
      - "3306:3306"  
    networks:
      - my_network

volumes:
  mysql-data:

networks:
  my_network:
    driver: bridge
