version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2000  
      POSTGRES_DB: infinum_chat
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infinum_chat.sql:/docker-entrypoint-initdb.d/infinum_chat.sql
    ports:
      - "5432:5432"
    networks:
      - my_network

  backend:
    build: ../backend
    container_name: backend-app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - my_network
    environment:
      - DATABASE_HOST=postgres 
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=2000  
      - DATABASE_NAME=infinum_chat

  frontend:
    build: ../frontend
    container_name: frontend-app
    depends_on:
      - backend
    ports:
      - "8501:8501"
    networks:
      - my_network

volumes:
  postgres-data:

networks:
  my_network:
    driver: bridge
